### ISSUE TITLE
Exception thrown when ran without config file

### ISSUE THREAD

**Issue by BrechtSerckx** [fogine/i3-workscreen#2]
Exception is thrown when running i3-workscreen without configuration file
```
user@host ~ % i3-workscreen 
Traceback (most recent call last):
  File "/home/brecht/.local/lib/python3.6/site-packages/i3_workscreen-0.1-py3.6.egg/i3workscreen/i3workscreen.py", line 78, in get_config
FileNotFoundError: [Errno 2] No such file or directory: '/home/brecht/.config/i3-workscreen/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brecht/.local/bin/i3-workscreen", line 11, in <module>
    load_entry_point('i3-workscreen==0.1', 'console_scripts', 'i3-workscreen')()
  File "/home/brecht/.local/lib/python3.6/site-packages/i3_workscreen-0.1-py3.6.egg/i3workscreen/i3workscreen.py", line 166, in main
  File "/home/brecht/.local/lib/python3.6/site-packages/i3_workscreen-0.1-py3.6.egg/i3workscreen/i3workscreen.py", line 82, in get_config
RuntimeError: Missing required config.json at /home/brecht/.config/i3-workscreen/config.json
```

**Comment by fogine** [comment]
It should have failed with the message without the trace log, will fix that.
The failure is currently by design as there is nothing to do without the configuration file.
Would you prefer different behavior?
Thank you for the feedback.

**Comment by BrechtSerckx** [comment]
I think an simple message "No configuration file found at /home/user/.config/i3-workscreen/config.json" would be good. 
It would be better than erroring out
