### ISSUE TITLE
Exception thrown despite config file

### ISSUE THREAD

**Issue by ghost** [fogine/i3-workscreen#5]
Hey,

i followed the instructions in the README and i'm getting this tracelog.

```
i3-workscreen 
Traceback (most recent call last):
  File "/usr/bin/i3-workscreen", line 11, in <module>
    load_entry_point('i3-workscreen==0.1', 'console_scripts', 'i3-workscreen')()
  File "/usr/lib/python3.7/site-packages/i3workscreen/i3workscreen.py", line 200, in main
    outputCloneCandidate = getCloneCandidate(connectedOutputs)
  File "/usr/lib/python3.7/site-packages/i3workscreen/i3workscreen.py", line 133, in getCloneCandidate
    return outputs[0]
IndexError: list index out of range
```
I adjusted the path to my user's home in the udev rules.
My config looks something like:
```json
 {
    "disableEmptyOutputs": true,
    "outputs": [
        {
            "name": "eDP-1",
            "workspaces": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "0" ]
        },
        {
            "name": "HDMI-1",
            "xrandr": ["--right-of", "eDP-1"],
            "workspaces": [ "1", "2", "3", "4" ]
        },
        {
            "name": "DP-2",
            "xrandr": ["--right-of", "HDMI-1"],
            "workspaces": ["5", "6", "7", "8", "9"]
        }
    ]
}
```
Suffice it to say, it doesn't apply the config when I disconnect the laptop from my docking station.

**Comment by fogine** [comment]
Whats the contents of `98-monitor-hotplug.rules` exactly?

Looks like the `i3-workscreen` is run when no displays are connected/detected.
Currently it assumes laptop's display is always available as fallback. I could gracefully exit with error message that would inform the user about that. I'll do that.

**Comment by ghost** [comment]
Hey, thanks for the quick reply.
`98-monitor-hotplug.rules`
```udev
KERNEL=="card0", SUBSYSTEM=="drm", ACTION=="change", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/home/damrath/.Xauthority", ENV{HOME}="/home/damrath", RUN+="/bin/sh -c '/bin/ps -e | grep Xorg && /bin/i3-workscreen'"
```

Additionally, here is the output of `xrandr`
```
Screen 0: minimum 8 x 8, current 5760 x 1200, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+120 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     60.00*+  59.93    48.00  
   1680x1050     59.88  
   1400x1050     59.98  
   1600x900      60.00    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1368x768      60.00    59.88    59.85  
   1280x800      59.81    59.91  
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 connected 1920x1200+3840+0 (normal left inverted right x axis y axis) 520mm x 320mm
   1920x1200     59.95*+
   1920x1080     60.00    50.00    59.94    30.00    25.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
DP3 disconnected (normal left inverted right x axis y axis)
HDMI1 connected 1920x1200+1920+0 (normal left inverted right x axis y axis) 520mm x 320mm
   1920x1200     59.95*+
   1920x1080     50.00  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      74.98    59.90  
   1280x960      60.00  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
HDMI2 disconnected (normal left inverted right x axis y axis)
HDMI3 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

Could there be something wrong with my `.i3/config`?
I have an `xrandr` command in it that applies the multi-monitor layout.
Maybe that is interfering with `i3-workscreen`?

**Comment by fogine** [comment]
The udev event is emitted way too early on a system startup before the `X.org` server is running so you need to execute `i3-workscreen` in `i3/config` as well (in order to make it work on system (re)start).  

I've updated documentation and made additional changes regarding exception you provided in [#5-fix branch](https://github.com/fogine/i3-workscreen/tree/%235-fix). Could you test that?  

I recommend disabling all your scripts regarding `xrandr` in your `i3/config` to make sure they wont collide.
